spring:
  application:
    name: credit-api
  datasource:
    url: jdbc:mysql://localhost:3306/credit-api?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  expiration: 86400000 # 24 hrs
  key: "c4a83e9b1d5f2a7e2s23no35b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c}"